Locking feature addition
UniversalGRAMM/UGRAMM pull request #20
Opened 2024-10-14 17:50 UTC by HamasWaqar

In brief, this branch incorporates node locking for UGRAMM. Locking is a feature that restricts a specific application graph node to be mapped only to a subset of nodes in the device model graph. In GRAMM, locking is entirely based on the node names of both the application graph and the device model graph, allowing for abstract and flexible use of this tool.

To lock nodes, users must list all the nodes in the config.json under the "lock-nodes" tag shown below. 
`"lock-nodes" : [<-String list of locked nodes->]; `

In addition, locked nodes must be written in the format `hName::gName`, as shown in the example below. The two colons (::) in the locking format are used to clearly distinguish between `hNames` (application graph node) and `gNames` (device model node). Without the colons, the UGRAMM mapper will not be able to identify which application graph node is locked to which device model node, potentially leading to unexpected results or errors.

`"lock-nodes" : ["FMUL_9::pe.w32.c4.r6.alu", "FMUL_11::pe.w32.c4.r4.alu", "FMUL_13::pe.w32.c2.r4.alu"]`

By default, UGRAMM supports one-to-one node locking, meaning each application graph node must be locked to only one device model node. This is achieved by providing the full `gName` of the device model node (assuming each `gName` is unique). However, UGRAMM also supports locking an application graph node to multiple device model nodes using a wildcard operator (`*`). Similar to how wildcards are used in Linux terminals, users only need to provide a common string name surrounded by the `*`.

Below are a few examples of how wildcard operators can be used for node locking. For this example, we are using the 8x8 RIKEN CGRA architecture, where each Processing Element (PE) is defined by rows (`r`) and columns (`c`). Each PE contains both an ALU and a constant.

In the example `FMUL_9::*c4*`, the node `FMUL_9` must be locked to any suitable function cell with `c4` in its `gName`. The UGRAMM mapper will attempt to map `FMUL_9 `to one of these function cells while minimizing the routing cost.

In the example `FMUL_13::*r4*alu`, the UGRAMM mapper will map `FMUL_13` to one of the function cells with `r4` followed by `alu` in its `gName`, while also minimizing the routing cost. Note that the order of substrings must match exactly in the `gName`, meaning `r4` must appear before `alu` in the example.

`"lock-nodes" : ["FMUL_9::*c4*", "FMUL_13::*r4*alu"]`

To enable wildcard locking, users must set the `allowWildcardInLocking` define statement to `1` in UGRAMM.h. 

------------------

Other changes have been made in this branch. 

1. By default, UGRAMM mappers randomize the mapping of application DFG nodes to reduce mapping time. However, UGRAMM can prioritize mapping nodes with constraints first, such as locked nodes in this example. This feature is enabled by default, but if users wish to disable it, they can do so by setting the `sortAlgorithm` define statement in UGRAMM.h to `0`.

2. When mapping application DFG nodes that are not locked, UGRAMM will, by default, skip over device model nodes that are potentially locked, as indicated in the lock-nodes tab of the config file. This approach helps reduce runtime. Note that this only applies to locked nodes with a one-to-one mapping between the application DFG node and the device model node (i.e., not using the wildcard operator). To disable this feature, users can set the `skipFullyLockedNodes` define statement to `0` in UGRAMM.h.

3. Addition DRC for locking nodes. Note that the DRC rules only apply to locked nodes with a one-to-one mapping between the application DFG node and the device model node (i.e., not using the wildcard operator). These rule checks are:
- Check if the multiple application DFG nodes are attempting to map to one device model node
- Check if the nodeType of the device model graph is suitable for the locked application DFG node

4. Added optional command line option to (1) disable the DRC checks through `--drc_disable` and (2) adjust the DRC message verbose level by `--drc_verbose_level=1`. For `--drc_verbose_level`, the verbose is defined as `0 -> err [default]`,  ` 1-> warn`,  and `2-> info`.

5. Added a secondary spdlogger for the DRC. Please note that the secondary spdlogger must be initialized in UGRAMM.h. I initially attempted to initialize it in DRC.h, but after a few changes with make, the pointer became misaligned and failed. Even after running make clean, the pointer mismatch persisted. The permanent solution to avoid these errors is to initialize the secondary spdlogger in UGRAMM.h, where the primary spdlogger for UGRAMM is also initialized.
https://github.com/UniversalGRAMM/UGRAMM/blob/c7cac1870e5a55f11e477245ade128cc5a3571a4/lib/UGRAMM.h#L125-L126C8

6. As noted in issue #17, pin names were not case-insensitive. In this branch, I made changes to ensure that pin names are now case-insensitive.

2024-10-14 17:52 UTC, HamasWaqar commented on lib/UGRAMM.h
> +extern std::shared_ptr<spdlog::logger> drcLogger;
This is the initialization of the secondary spdlogger as mentioned in point 5 above.

2024-10-14 17:53 UTC, HamasWaqar commented
@ombhilare999 Could you review this? I will also create a pull request for the benchmarks.

2024-10-15 04:35 UTC, ombhilare999 commented
Hi @HamasWaqar,

I am not able to run the UGRAMM on this branch `locking_new`, what command are you using to run UGRAMM?

>  ./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json

If I try above command, I am observing the following error:

```
---------------------Executing UGRAMM and producing mapping result in ordered_dot_output.dot & unpositioned_dot_output---------------------
make && ./UGRAMM --seed 0 --verbose_level 0 --dfile scripts/riken_8_8.dot --afile Kernels/Conv_Balance/conv_nounroll_Balance.dot --config config.json --drc_verbose_level 1
make: 'UGRAMM' is up to date.
[2024-10-15 00:30:51.363] [UGRAMM] [info] Parsed JSON file {"lock-nodes":["FMUL_9::pe.w32.c4.r6.alu","FMUL_11::pe.w32.c4.r4.alu","FMUL_13::pe.w32.c2"],"skip-placement":["Constant"]} 
[2024-10-15 00:30:51.364] [UGRAMM] [info] Normalized JSON {"LOCK-NODES":["FMUL_9::PE.W32.C4.R6.ALU","FMUL_11::PE.W32.C4.R4.ALU","FMUL_13::PE.W32.C2"],"SKIP-PLACEMENT":["CONSTANT"]} 
[2024-10-15 00:30:51.364] [UGRAMM] [info] Parsed Device-Model Pragma: 
[ALU] :: ALU :: FADD :: FSUB :: FMUL :: FDIV
[CONSTANT] :: CONSTANT :: CONST
[MEMPORT] :: MEMPORT :: INPUT :: OUTPUT
[2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [ALU]
[2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FADD found in ALU
[2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FMUL found in ALU
[2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [CONSTANT]
[2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token CONST found in CONSTANT
[2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [MEMPORT]
[2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token INPUT found in MEMPORT
[2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token OUTPUT found in MEMPORT
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_27|float32=5.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_28|float32=13.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_29|float32=9.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_30|float32=11.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_31|float32=3.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_32|float32=15.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_33|float32=17.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_34|float32=7.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_35|float32=19.00} 
[2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_11 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R4.ALU
[2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_13 :: applicationOpcode FMUL :: GNode Lock PE.W32.C2
[2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_9 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R6.ALU
[2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
[2024-10-15 00:30:51.427] [DRC Checks] [info] Executing DRC Rules Check
[2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
[2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
[2024-10-15 00:30:51.737] [DRC Checks] [info] DRC Passed --- Continueing to UGRAMM Mapping
[2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
[2024-10-15 00:30:51.737] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 1
[2024-10-15 00:30:52.933] [UGRAMM] [info] TOTAL OVERUSE: 3
[2024-10-15 00:30:52.933] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 2
./run_ugramm.sh: line 43: 35972 Segmentation fault      (core dumped) ./UGRAMM --seed $1 --verbose_level $verbose_level --dfile $dfile --afile $afile --config $cfile
 
 
---------------------Converting the ordered-mapped  positioned_dot_output.dot file into positioned_dot_output.png:---------------------
neato -Tpng positioned_dot_output.dot -o positioned_dot_output.png
Error: neato: can't open positioned_dot_output.dot
 
 
---------------------Converting the unordered-mapped  unpositioned_dot_output.dot file into unpositioned_dot_output.png:---------------------
neato -Tpng unpositioned_dot_output.dot -o unpositioned_dot_output.png
Error: dot: can't open unpositioned_dot_output.dot
```

Also, why we have commented following line in the helper script:
https://github.com/UniversalGRAMM/UGRAMM/blob/c7cac1870e5a55f11e477245ade128cc5a3571a4/run_ugramm.sh#L27
similar like the `verbose_level` [This can be renamed to `ugramm_verbose_level` ] we can provide the verbosity level as variable in the script, so it is very easy to modify for different runs.

Also, I see that in the helper script you haven't pass the verbosity level for DRC, maybe that's why this segmentation fault occurred.

![image](https://github.com/user-attachments/assets/8cad564d-d860-49f3-ac91-88e804373eff)

2024-10-15 04:45 UTC, ombhilare999 requested changes

2024-10-15 04:45 UTC, ombhilare999 commented on scripts/device_model_gen.py
> -            MUX_NAME  = ["S", "SW", "W", "NW", "N", "NE", "E", "SE", "PEinA", "PEinB"]
Also, regarding all the changes in the `device_model_gen.py`. If we are not using the `Placement X/Y` co-ordinates  to lock a particular application node onto device model node, can we remove **ALL** of the changes and revert back to the master version of the script in this PR.

Cause, I see some of the changes which I added in the master regarding this script are being removed in this script.

Ref: 
https://github.com/UniversalGRAMM/UGRAMM/blob/396efc291fc5718655212b515e8442db8b9873bc/scripts/device_model_gen.py#L389-L400

2024-10-15 04:46 UTC, ombhilare999 commented on src/UGRAMM.cpp
>    double secondsDRC;
Nitpick: Can we define `secondsDRC` only when DRC is not disabled?

2024-10-15 04:58 UTC, ombhilare999 commented on Kernels/Conv_Balance/conv_nounroll_Balance.dot
> +FMUL_9 [label="{FMUL_9}", opcode=FMUL, shape=record, type=op, lockGNode="pe.w32.c4.r6.alu"];
Just to confirm that we are on same note, this `lockGNode` attribute is no longer being used and will be removed by your next PR #21 ?
Is that correct?

2024-10-15 05:16 UTC, ombhilare999 commented on lib/UGRAMM.h
> +#define skipFullyLockedNodes 1    //Skip fully locked nodes when mapping application nodes that are not locked (1 --> Skip Fully Locked Nodes, 0 --> otherwise)
I'm curious about the performance of UGRAMM when we skip fully locked nodes instead of considering them. Could we potentially find better solutions by allowing a locked location to be temporarily occupied by an application node other than its designated counterpart? In this approach, the other node could occupy the position for a brief phase but would later have to settle nearby, since the position wasn't permanently locked for it. This method seems more advantageous in terms of optimizing routing resources. Do you have any data on this, or should we consider testing it in a future experimental run?

2024-10-15 05:17 UTC, ombhilare999 commented on lib/UGRAMM.h
> +    std::string H_LockGNode;  //[Optional] Contains the name of the G Node for locking
Is this still being used?

2024-10-15 05:26 UTC, ombhilare999 commented on lib/UGRAMM.h
> +extern std::map<std::string, int> gNamesInv_FuncCell;   // Inverse map for getting GID using the unique names of device model graph. Map only funcCell in gNames
Hi,
Are we using both of the above data structures?
If we are not using let's say `gNamesInv`, then can we remove it maybe?

2024-10-15 16:57 UTC, HamasWaqar commented
> Hi @HamasWaqar,
> 
> I am not able to run the UGRAMM on this branch `locking_new`, what command are you using to run UGRAMM?
> 
> > ./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json
> 
> If I try above command, I am observing the following error:
> 
> ```
> ---------------------Executing UGRAMM and producing mapping result in ordered_dot_output.dot & unpositioned_dot_output---------------------
> make && ./UGRAMM --seed 0 --verbose_level 0 --dfile scripts/riken_8_8.dot --afile Kernels/Conv_Balance/conv_nounroll_Balance.dot --config config.json --drc_verbose_level 1
> make: 'UGRAMM' is up to date.
> [2024-10-15 00:30:51.363] [UGRAMM] [info] Parsed JSON file {"lock-nodes":["FMUL_9::pe.w32.c4.r6.alu","FMUL_11::pe.w32.c4.r4.alu","FMUL_13::pe.w32.c2"],"skip-placement":["Constant"]} 
> [2024-10-15 00:30:51.364] [UGRAMM] [info] Normalized JSON {"LOCK-NODES":["FMUL_9::PE.W32.C4.R6.ALU","FMUL_11::PE.W32.C4.R4.ALU","FMUL_13::PE.W32.C2"],"SKIP-PLACEMENT":["CONSTANT"]} 
> [2024-10-15 00:30:51.364] [UGRAMM] [info] Parsed Device-Model Pragma: 
> [ALU] :: ALU :: FADD :: FSUB :: FMUL :: FDIV
> [CONSTANT] :: CONSTANT :: CONST
> [MEMPORT] :: MEMPORT :: INPUT :: OUTPUT
> [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [ALU]
> [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FADD found in ALU
> [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FMUL found in ALU
> [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [CONSTANT]
> [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token CONST found in CONSTANT
> [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [MEMPORT]
> [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token INPUT found in MEMPORT
> [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token OUTPUT found in MEMPORT
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_27|float32=5.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_28|float32=13.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_29|float32=9.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_30|float32=11.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_31|float32=3.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_32|float32=15.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_33|float32=17.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_34|float32=7.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_35|float32=19.00} 
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_11 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R4.ALU
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_13 :: applicationOpcode FMUL :: GNode Lock PE.W32.C2
> [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_9 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R6.ALU
> [2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
> [2024-10-15 00:30:51.427] [DRC Checks] [info] Executing DRC Rules Check
> [2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
> [2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
> [2024-10-15 00:30:51.737] [DRC Checks] [info] DRC Passed --- Continueing to UGRAMM Mapping
> [2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
> [2024-10-15 00:30:51.737] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 1
> [2024-10-15 00:30:52.933] [UGRAMM] [info] TOTAL OVERUSE: 3
> [2024-10-15 00:30:52.933] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 2
> ./run_ugramm.sh: line 43: 35972 Segmentation fault      (core dumped) ./UGRAMM --seed $1 --verbose_level $verbose_level --dfile $dfile --afile $afile --config $cfile
>  
>  
> ---------------------Converting the ordered-mapped  positioned_dot_output.dot file into positioned_dot_output.png:---------------------
> neato -Tpng positioned_dot_output.dot -o positioned_dot_output.png
> Error: neato: can't open positioned_dot_output.dot
>  
>  
> ---------------------Converting the unordered-mapped  unpositioned_dot_output.dot file into unpositioned_dot_output.png:---------------------
> neato -Tpng unpositioned_dot_output.dot -o unpositioned_dot_output.png
> Error: dot: can't open unpositioned_dot_output.dot
> ```
> 
> Also, why we have commented following line in the helper script:
> 
> https://github.com/UniversalGRAMM/UGRAMM/blob/c7cac1870e5a55f11e477245ade128cc5a3571a4/run_ugramm.sh#L27
> 
> 
> similar like the `verbose_level` [This can be renamed to `ugramm_verbose_level` ] we can provide the verbosity level as variable in the script, so it is very easy to modify for different runs.
> Also, I see that in the helper script you haven't pass the verbosity level for DRC, maybe that's why this segmentation fault occurred.
> 
> ![image](https://private-user-images.githubusercontent.com/40693854/376458753-8cad564d-d860-49f3-ac91-88e804373eff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTA2NzcsIm5iZiI6MTcyOTAxMDM3NywicGF0aCI6Ii80MDY5Mzg1NC8zNzY0NTg3NTMtOGNhZDU2NGQtZDg2MC00OWYzLWFjOTEtODhlODA0MzczZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE2MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODIwMTA0YTBkZTlhZWEyZWU2YzgyMjNmYjc1YTZiODUzNGM3YzY1MjNiNGI5ODBlYzRiOWJlMmViYWMxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vjYLV0yKeDXo9tdO8Va7NAGWse8xcpBrtICPYJkqgWM)

To get to the execution issue: did you make clean and then make? I was able to run the command `./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json` on my side. 

Regarding the commenting out the `verbose_level` in the helper script, this is a typo that I'll fixed now.

2024-10-15 17:00 UTC, HamasWaqar commented on scripts/device_model_gen.py
> -            MUX_NAME  = ["S", "SW", "W", "NW", "N", "NE", "E", "SE", "PEinA", "PEinB"]
Yes, I'll fix this.

2024-10-15 17:01 UTC, HamasWaqar commented on src/UGRAMM.cpp
>    double secondsDRC;
Ok, I'll work on this.

2024-10-15 17:02 UTC, HamasWaqar commented on Kernels/Conv_Balance/conv_nounroll_Balance.dot
> +FMUL_9 [label="{FMUL_9}", opcode=FMUL, shape=record, type=op, lockGNode="pe.w32.c4.r6.alu"];
I'll remove this --- forgot to revert this back to the original.

2024-10-15 17:11 UTC, HamasWaqar commented on lib/UGRAMM.h
> +#define skipFullyLockedNodes 1    //Skip fully locked nodes when mapping application nodes that are not locked (1 --> Skip Fully Locked Nodes, 0 --> otherwise)
That is a good point. Unfortunately, I don't have any experimental data on this, though, we can easily modify the code to test this out. For now, let's try to push this code in UGRAMM for Luios work, but I'll work on this after the merge on a separate branch.

2024-10-15 17:14 UTC, HamasWaqar commented on lib/UGRAMM.h
> +    std::string H_LockGNode;  //[Optional] Contains the name of the G Node for locking
Yes, this is the string that keeps track of what gNode name the current application node is locked into. This is one of the core components in implementing the locking feature in UGRAMM. H_PlacementX and H_PlacementY is not being used hence, removed.

2024-10-15 17:15 UTC, HamasWaqar commented on lib/UGRAMM.h
> +extern std::map<std::string, int> gNamesInv_FuncCell;   // Inverse map for getting GID using the unique names of device model graph. Map only funcCell in gNames
We are currently not using the gNamesInv data structure. I thought to keep it in the code as I feel it could be used for other constraints when we add them or if we want to enable locking to routing cells.

2024-10-16 14:35 UTC, HamasWaqar commented
> > Hi @HamasWaqar,
> > I am not able to run the UGRAMM on this branch `locking_new`, what command are you using to run UGRAMM?
> > > ./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json
> > 
> > 
> > If I try above command, I am observing the following error:
> > ```
> > ---------------------Executing UGRAMM and producing mapping result in ordered_dot_output.dot & unpositioned_dot_output---------------------
> > make && ./UGRAMM --seed 0 --verbose_level 0 --dfile scripts/riken_8_8.dot --afile Kernels/Conv_Balance/conv_nounroll_Balance.dot --config config.json --drc_verbose_level 1
> > make: 'UGRAMM' is up to date.
> > [2024-10-15 00:30:51.363] [UGRAMM] [info] Parsed JSON file {"lock-nodes":["FMUL_9::pe.w32.c4.r6.alu","FMUL_11::pe.w32.c4.r4.alu","FMUL_13::pe.w32.c2"],"skip-placement":["Constant"]} 
> > [2024-10-15 00:30:51.364] [UGRAMM] [info] Normalized JSON {"LOCK-NODES":["FMUL_9::PE.W32.C4.R6.ALU","FMUL_11::PE.W32.C4.R4.ALU","FMUL_13::PE.W32.C2"],"SKIP-PLACEMENT":["CONSTANT"]} 
> > [2024-10-15 00:30:51.364] [UGRAMM] [info] Parsed Device-Model Pragma: 
> > [ALU] :: ALU :: FADD :: FSUB :: FMUL :: FDIV
> > [CONSTANT] :: CONSTANT :: CONST
> > [MEMPORT] :: MEMPORT :: INPUT :: OUTPUT
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [ALU]
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FADD found in ALU
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token FMUL found in ALU
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [CONSTANT]
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token CONST found in CONSTANT
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] Checking compatibility of SupportedOps of [MEMPORT]
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token INPUT found in MEMPORT
> > [2024-10-15 00:30:51.426] [UGRAMM] [info] [PASSED] The token OUTPUT found in MEMPORT
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_27|float32=5.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_28|float32=13.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_29|float32=9.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_30|float32=11.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_31|float32=3.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_32|float32=15.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_33|float32=17.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_34|float32=7.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_35|float32=19.00} 
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_11 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R4.ALU
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_13 :: applicationOpcode FMUL :: GNode Lock PE.W32.C2
> > [2024-10-15 00:30:51.427] [UGRAMM] [info] [Locking] [H] name FMUL_9 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R6.ALU
> > [2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
> > [2024-10-15 00:30:51.427] [DRC Checks] [info] Executing DRC Rules Check
> > [2024-10-15 00:30:51.427] [DRC Checks] [info] --------------------------------------------------
> > [2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
> > [2024-10-15 00:30:51.737] [DRC Checks] [info] DRC Passed --- Continueing to UGRAMM Mapping
> > [2024-10-15 00:30:51.737] [DRC Checks] [info] --------------------------------------------------
> > [2024-10-15 00:30:51.737] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 1
> > [2024-10-15 00:30:52.933] [UGRAMM] [info] TOTAL OVERUSE: 3
> > [2024-10-15 00:30:52.933] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 2
> > ./run_ugramm.sh: line 43: 35972 Segmentation fault      (core dumped) ./UGRAMM --seed $1 --verbose_level $verbose_level --dfile $dfile --afile $afile --config $cfile
> >  
> >  
> > ---------------------Converting the ordered-mapped  positioned_dot_output.dot file into positioned_dot_output.png:---------------------
> > neato -Tpng positioned_dot_output.dot -o positioned_dot_output.png
> > Error: neato: can't open positioned_dot_output.dot
> >  
> >  
> > ---------------------Converting the unordered-mapped  unpositioned_dot_output.dot file into unpositioned_dot_output.png:---------------------
> > neato -Tpng unpositioned_dot_output.dot -o unpositioned_dot_output.png
> > Error: dot: can't open unpositioned_dot_output.dot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, why we have commented following line in the helper script:
> > https://github.com/UniversalGRAMM/UGRAMM/blob/c7cac1870e5a55f11e477245ade128cc5a3571a4/run_ugramm.sh#L27
> > 
> > similar like the `verbose_level` [This can be renamed to `ugramm_verbose_level` ] we can provide the verbosity level as variable in the script, so it is very easy to modify for different runs.
> > Also, I see that in the helper script you haven't pass the verbosity level for DRC, maybe that's why this segmentation fault occurred.
> > ![image](https://private-user-images.githubusercontent.com/40693854/376458753-8cad564d-d860-49f3-ac91-88e804373eff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTA2NzcsIm5iZiI6MTcyOTAxMDM3NywicGF0aCI6Ii80MDY5Mzg1NC8zNzY0NTg3NTMtOGNhZDU2NGQtZDg2MC00OWYzLWFjOTEtODhlODA0MzczZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE2MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODIwMTA0YTBkZTlhZWEyZWU2YzgyMjNmYjc1YTZiODUzNGM3YzY1MjNiNGI5ODBlYzRiOWJlMmViYWMxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vjYLV0yKeDXo9tdO8Va7NAGWse8xcpBrtICPYJkqgWM)
> 
> To get to the execution issue: did you make clean and then make? I was able to run the command `./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json` on my side.
> 
> Regarding the commenting out the `verbose_level` in the helper script, this is a typo that I'll fixed now.

Hi @ombhilare999, could you provide more details to I can test the compilation and execution issue you are facing? I am able to run the code on my end perfectly.

2024-10-16 16:39 UTC, ombhilare999 commented
Hi @HamasWaqar,

I used the following sequence of comments:

```
git clone git@github.com:UniversalGRAMM/UGRAMM.git
cd UGRAMM
git checkout locking_new
make clean
make
./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json > log.out
```

**log.out:**

```
---------------------Generating device model using external script:---------------------
cd scripts && ./device_model_gen.py -NR 8 -NC 8 -Arch RIKEN && cd ..
====================================================
============ Universal GRAMM (UGRAMM) ==============
======= helper script: Device Model Generator ======
====================================================

Generating device model for the following CGRA configuration: 
> Arch: RIKEN
> NR: 8
> NC: 8
Creating RIKEN architecture!!


pragma for the device model: 

 /* ------- Device model pragma ------- 
[SupportedOps] = {ALU, FADD, FSUB, FMUL, FDIV}; 
[SupportedOps] = {MemPort, INPUT, OUTPUT}; 
[SupportedOps] = {Constant, CONST}; 
*/

 
 
---------------------Executing UGRAMM and producing mapping result in ordered_dot_output.dot & unpositioned_dot_output---------------------
make && ./UGRAMM --seed 0 --verbose_level 0 --dfile scripts/riken_8_8.dot --afile Kernels/Conv_Balance/conv_nounroll_Balance.dot --config config.json --drc_verbose_level 1
make: 'UGRAMM' is up to date.
[2024-10-16 12:38:11.671] [UGRAMM] [info] Parsed JSON file {"lock-nodes":["FMUL_9::pe.w32.c4.r6.alu","FMUL_11::pe.w32.c4.r4.alu","FMUL_13::pe.w32.c2"],"skip-placement":["Constant"]} 
[2024-10-16 12:38:11.671] [UGRAMM] [info] Normalized JSON {"LOCK-NODES":["FMUL_9::PE.W32.C4.R6.ALU","FMUL_11::PE.W32.C4.R4.ALU","FMUL_13::PE.W32.C2"],"SKIP-PLACEMENT":["CONSTANT"]} 
[2024-10-16 12:38:11.671] [UGRAMM] [info] Parsed Device-Model Pragma: 
[ALU] :: ALU :: FADD :: FSUB :: FMUL :: FDIV
[CONSTANT] :: CONSTANT :: CONST
[MEMPORT] :: MEMPORT :: INPUT :: OUTPUT
[2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [ALU]
[2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token FADD found in ALU
[2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token FMUL found in ALU
[2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [CONSTANT]
[2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token CONST found in CONSTANT
[2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [MEMPORT]
[2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token INPUT found in MEMPORT
[2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token OUTPUT found in MEMPORT
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_27|float32=5.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_28|float32=13.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_29|float32=9.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_30|float32=11.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_31|float32=3.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_32|float32=15.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_33|float32=17.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_34|float32=7.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_35|float32=19.00} 
[2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_11 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R4.ALU
[2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_13 :: applicationOpcode FMUL :: GNode Lock PE.W32.C2
[2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_9 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R6.ALU
[2024-10-16 12:38:11.729] [DRC Checks] [info] --------------------------------------------------
[2024-10-16 12:38:11.729] [DRC Checks] [info] Executing DRC Rules Check
[2024-10-16 12:38:11.729] [DRC Checks] [info] --------------------------------------------------
[2024-10-16 12:38:12.044] [DRC Checks] [info] --------------------------------------------------
[2024-10-16 12:38:12.044] [DRC Checks] [info] DRC Passed --- Continueing to UGRAMM Mapping
[2024-10-16 12:38:12.044] [DRC Checks] [info] --------------------------------------------------
[2024-10-16 12:38:12.045] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 1
[2024-10-16 12:38:13.381] [UGRAMM] [info] TOTAL OVERUSE: 3
[2024-10-16 12:38:13.381] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 2
./run_ugramm.sh: line 43: 27475 Segmentation fault      (core dumped) ./UGRAMM --seed $1 --verbose_level $verbose_level --dfile $dfile --afile $afile --config $cfile
 
 
---------------------Converting the ordered-mapped  positioned_dot_output.dot file into positioned_dot_output.png:---------------------
neato -Tpng positioned_dot_output.dot -o positioned_dot_output.png
Error: neato: can't open positioned_dot_output.dot
 
 
---------------------Converting the unordered-mapped  unpositioned_dot_output.dot file into unpositioned_dot_output.png:---------------------
neato -Tpng unpositioned_dot_output.dot -o unpositioned_dot_output.png
Error: dot: can't open unpositioned_dot_output.dot
```

Not sure what's wrong in this scenario.

2024-10-16 20:37 UTC, HamasWaqar commented
> Hi @HamasWaqar,
> 
> I used the following sequence of comments:
> 
> ```
> git clone git@github.com:UniversalGRAMM/UGRAMM.git
> cd UGRAMM
> git checkout locking_new
> make clean
> make
> ./run_ugramm.sh 0 8 8 Kernels/Conv_Balance/conv_nounroll_Balance.dot config.json >& log.out
> ```
> 
> **log.out:**
> 
> ```
> ---------------------Generating device model using external script:---------------------
> cd scripts && ./device_model_gen.py -NR 8 -NC 8 -Arch RIKEN && cd ..
> ====================================================
> ============ Universal GRAMM (UGRAMM) ==============
> ======= helper script: Device Model Generator ======
> ====================================================
> 
> Generating device model for the following CGRA configuration: 
> > Arch: RIKEN
> > NR: 8
> > NC: 8
> Creating RIKEN architecture!!
> 
> 
> pragma for the device model: 
> 
>  /* ------- Device model pragma ------- 
> [SupportedOps] = {ALU, FADD, FSUB, FMUL, FDIV}; 
> [SupportedOps] = {MemPort, INPUT, OUTPUT}; 
> [SupportedOps] = {Constant, CONST}; 
> */
> 
>  
>  
> ---------------------Executing UGRAMM and producing mapping result in ordered_dot_output.dot & unpositioned_dot_output---------------------
> make && ./UGRAMM --seed 0 --verbose_level 0 --dfile scripts/riken_8_8.dot --afile Kernels/Conv_Balance/conv_nounroll_Balance.dot --config config.json --drc_verbose_level 1
> make: 'UGRAMM' is up to date.
> [2024-10-16 12:38:11.671] [UGRAMM] [info] Parsed JSON file {"lock-nodes":["FMUL_9::pe.w32.c4.r6.alu","FMUL_11::pe.w32.c4.r4.alu","FMUL_13::pe.w32.c2"],"skip-placement":["Constant"]} 
> [2024-10-16 12:38:11.671] [UGRAMM] [info] Normalized JSON {"LOCK-NODES":["FMUL_9::PE.W32.C4.R6.ALU","FMUL_11::PE.W32.C4.R4.ALU","FMUL_13::PE.W32.C2"],"SKIP-PLACEMENT":["CONSTANT"]} 
> [2024-10-16 12:38:11.671] [UGRAMM] [info] Parsed Device-Model Pragma: 
> [ALU] :: ALU :: FADD :: FSUB :: FMUL :: FDIV
> [CONSTANT] :: CONSTANT :: CONST
> [MEMPORT] :: MEMPORT :: INPUT :: OUTPUT
> [2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [ALU]
> [2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token FADD found in ALU
> [2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token FMUL found in ALU
> [2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [CONSTANT]
> [2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token CONST found in CONSTANT
> [2024-10-16 12:38:11.727] [UGRAMM] [info] Checking compatibility of SupportedOps of [MEMPORT]
> [2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token INPUT found in MEMPORT
> [2024-10-16 12:38:11.727] [UGRAMM] [info] [PASSED] The token OUTPUT found in MEMPORT
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_27|float32=5.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_28|float32=13.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_29|float32=9.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_30|float32=11.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_31|float32=3.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_32|float32=15.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_33|float32=17.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_34|float32=7.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [H] Ignoring placement for application node :: {Const_35|float32=19.00} 
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_11 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R4.ALU
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_13 :: applicationOpcode FMUL :: GNode Lock PE.W32.C2
> [2024-10-16 12:38:11.728] [UGRAMM] [info] [Locking] [H] name FMUL_9 :: applicationOpcode FMUL :: GNode Lock PE.W32.C4.R6.ALU
> [2024-10-16 12:38:11.729] [DRC Checks] [info] --------------------------------------------------
> [2024-10-16 12:38:11.729] [DRC Checks] [info] Executing DRC Rules Check
> [2024-10-16 12:38:11.729] [DRC Checks] [info] --------------------------------------------------
> [2024-10-16 12:38:12.044] [DRC Checks] [info] --------------------------------------------------
> [2024-10-16 12:38:12.044] [DRC Checks] [info] DRC Passed --- Continueing to UGRAMM Mapping
> [2024-10-16 12:38:12.044] [DRC Checks] [info] --------------------------------------------------
> [2024-10-16 12:38:12.045] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 1
> [2024-10-16 12:38:13.381] [UGRAMM] [info] TOTAL OVERUSE: 3
> [2024-10-16 12:38:13.381] [UGRAMM] [info] ***** BEGINNING OUTER WHILE LOOP ***** ITER 2
> ./run_ugramm.sh: line 43: 27475 Segmentation fault      (core dumped) ./UGRAMM --seed $1 --verbose_level $verbose_level --dfile $dfile --afile $afile --config $cfile
>  
>  
> ---------------------Converting the ordered-mapped  positioned_dot_output.dot file into positioned_dot_output.png:---------------------
> neato -Tpng positioned_dot_output.dot -o positioned_dot_output.png
> Error: neato: can't open positioned_dot_output.dot
>  
>  
> ---------------------Converting the unordered-mapped  unpositioned_dot_output.dot file into unpositioned_dot_output.png:---------------------
> neato -Tpng unpositioned_dot_output.dot -o unpositioned_dot_output.png
> Error: dot: can't open unpositioned_dot_output.dot
> ```
> 
> Not sure what's wrong in this scenario.
> 
> Edit: Tested on TOFC and observing the similar error on the TOFC server as well.

@ombhilare999 Fixed this issue. Could you check if the update works on your end?

2024-10-17 02:32 UTC, ombhilare999 commented on lib/UGRAMM.h
> +    std::string H_LockGNode;  //[Optional] Contains the name of the G Node for locking
Hi @HamasWaqar,
When I search about this in our sourcode, I don't see this being used, can you re-confirm once?

```
❯ grep -nr "H_LockGNode" *
grep: build/drc.o: binary file matches
grep: build/utilities.o: binary file matches
grep: build/UGRAMM.o: binary file matches
grep: build/routing.o: binary file matches
lib/UGRAMM.h:65:    std::string H_LockGNode;  //[Optional] Contains the name of the G Node for locking
src/UGRAMM.cpp:462:  dp.property("lockGNode", boost::get(&DotVertex::H_LockGNode, H));        //--> [Required] Contains the property describing the fixed X location for placing the node
```

2024-10-17 02:34 UTC, ombhilare999 commented on lib/UGRAMM.h
> +extern std::map<std::string, int> gNamesInv_FuncCell;   // Inverse map for getting GID using the unique names of device model graph. Map only funcCell in gNames
Okay, can we add a comment in the source code as well regarding this; So it is easy to track the usuage of all the data structures we have defined.

2024-10-17 02:38 UTC, ombhilare999 commented on lib/UGRAMM.h
> +extern std::set<int> fullyLockedNodes;                  // List of Nodes that are fully locked (i.e. LockGNode for an application graph completely matches to a perticular gNames in device model graph
Hi,
A quick question, so does this fullyLockedNodes contain the information of locked node in the HID or GID format?

2024-10-17 02:42 UTC, ombhilare999 commented on src/UGRAMM.cpp
> +    }
Hi,
Can we execute this for loop only when the debugging level set to trace? In all of the levels right now the for loop will be iterated.
```
//-------- Debugging statements ------------//
if (UGRAMM->level() <= spdlog::level::trace)
    //Then only run the for loop!!
```

2024-10-17 02:43 UTC, ombhilare999 commented on src/UGRAMM.cpp
> +  dp.property("lockGNode", boost::get(&DotVertex::H_LockGNode, H));        //--> [Required] Contains the property describing the fixed X location for placing the node
Are we receiving the input of the Locknode from the config or from the application.dot?

2024-10-17 05:41 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +  dp.property("lockGNode", boost::get(&DotVertex::H_LockGNode, H));        //--> [Required] Contains the property describing the fixed X location for placing the node
We are receiving from the config file. I thought I removed that

2024-10-17 05:43 UTC, HamasWaqar commented on lib/UGRAMM.h
> +extern std::set<int> fullyLockedNodes;                  // List of Nodes that are fully locked (i.e. LockGNode for an application graph completely matches to a perticular gNames in device model graph
fullyLockedNodes contain the information of the GID. It is then used to skip over the locked GID nodes when mapping application nodes that are not locked

2024-10-17 05:43 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +    }
Will make that change

2024-10-17 05:45 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +  dp.property("lockGNode", boost::get(&DotVertex::H_LockGNode, H));        //--> [Required] Contains the property describing the fixed X location for placing the node
Also note, I removed the lockGNode attribute from the dot file in the #21

2024-10-17 05:48 UTC, ombhilare999 commented on src/UGRAMM.cpp
> +  dp.property("lockGNode", boost::get(&DotVertex::H_LockGNode, H));        //--> [Required] Contains the property describing the fixed X location for placing the node
Okay got it.

2024-10-17 05:52 UTC, ombhilare999 commented on src/utilities.cpp
> +   }
Hi @HamasWaqar,

Every time we find a locked HNode, I believe it is not necessary to iterate all the FuncCell G Nodes to find the correct locked G ID. Since we have already initialized `gNamesInv_FuncCell`, we can do something like this [Check my comments starting from `OB` ]:

```
    //Locking the device model nodes to a perticular node in the device model graph
    std::string jsonLockNode;
    if (getLockPE(i, jsonParsed, jsonLockNode)){
      std::string delimiter = "::";
      size_t pos = jsonLockNode.find(delimiter);
      if (pos != std::string::npos) {
        std::string ParsedGName   = boost::to_upper_copy(jsonLockNode.substr(pos + delimiter.length()));
        (*hConfig)[i].LockGNode = ParsedGName;
        int gInverseID  = gNamesInv_FuncCell[ParsedGName];  //OB: Parsing the gID using the inverse data-structure instead of itearting all of the functional cells in the G graph.
        UGRAMM->info("[Locking] [H] name {} :: applicationOpcode {} :: GNode Lock {} :: GNode Lock ID {}", hNames[i], upperCaseOpcode, ParsedGName, gInverseID);
      } else {
        UGRAMM->error(" Lock {} in the json file does not have \"::\" ", jsonLockNode);
      }
    }

    //Not Needed this then:
    /*
    // Storing the GID of nodes that are fully locked in set fullyLockedNodes. 
    // Fully locked noded means that LockGNode for an application graph completely matches to a perticular gNames in device model graph
    if (!(*hConfig)[i].LockGNode.empty()){
      for (const auto& pair : gNamesInv_FuncCell) {
        if ((*hConfig)[i].LockGNode == pair.first){
          UGRAMM->info("Locked Node {} :: gName {} :: GID {}", (*hConfig)[i].LockGNode, pair.first, pair.second);
          fullyLockedNodes.insert(pair.second);
        }
      }
    }
    */
```
This avoid the re-iteration of all of the FuncCell in the G graph, let me know if this makes sense. (I tested this in the code and it seems working, please re-confirm this, thanks.)

2024-10-17 05:54 UTC, ombhilare999 commented on src/utilities.cpp
> +    }
Also a similar trace guarded if statement before this debug-section would be more optimized way to go, lmk what you think.

2024-10-17 05:58 UTC, ombhilare999 commented on src/utilities.cpp
> +}
Hi @HamasWaqar,

I just noticied that we have a function defined in the `routing.cpp` which does the exact same thing. 

```
/*
 * Checks whether the current opcode required by the application node is supported by the device model node.
 * 
 * This function determines if the opcode needed by the application node (represented by `hOpcode`)
 * is compatible with or supported by the device model node type (represented by `gType`).
*/
bool compatibilityCheck(const std::string &gType, const std::string &hOpcode)
```

Let me know if we can omit the newly added function and use what we already have.

2024-10-17 06:01 UTC, ombhilare999 commented on src/utilities.cpp
> +bool getLockPE(int HID, json &jsonParsed, std::string& jsonLockNode)
Hi @HamasWaqar,

Can we rename this function? PE could be only specific to CGRA cases; How about needLocking() --> True means yes, the current HID needs to be locked; If not, skip the given loop and move to the next loop.

2024-10-17 06:27 UTC, ombhilare999 commented on src/UGRAMM.cpp
> +    int GID = findGNodeID_FuncCell((*hConfig)[y].LockGNode, suitableGIDs);
Hi @HamasWaqar,

Also in `findGNodeID_FuncCell`, we are iterating over all of the FuncCells available in the G graph, this makes sense for wildcard feature where there will be multiple suitable GIDs.
But for one-to-one match case, it seems strange to iterate over all of the cells in the G graph.

The following code will give you the same GID as well without iterating over all of the cells in the G graph, I checked this on my side, can you please re-confim?

> int gInverseID  = gNamesInv_FuncCell[(*hConfig)[y].LockGNode];

2024-10-17 06:35 UTC, ombhilare999 commented on src/UGRAMM.cpp
> +      }
Hi @HamasWaqar,

I believe we could do this in more optimized way, if all of the hNodes are locked then it will be very time consuming to search the entry in the entire large set.

How about we add a boolean variable `gLocked` in the NodeConfig, if we find earlier while parsing the H graph that a particular G node is locked then keeping this boolean variable `TRUE` and thus we can bypass these GIDs here easily by checking the node config.

```
//Struct for defining the node configuration in hConfig and gConfig data-structures:
struct NodeConfig {
    // For [G] --> Device Model Graph
    std::string Cell;          //Cell-type --> FuncCell, RouteCell, PinCell
    std::string Type;          //Node-Type --> io, alu, memport....
    int Latency = 0;           //Optional            
    bool gLocked;              //OB: True if the G is locked for a HNode; False otherwise!!
    
    // For [H] --> Application Graph
    std::string Opcode;        //OpcodeType --> FADD, FMUL, FSUB, INPUT, OUTPUT, etc.
    std::string pinName;       //Load pin of the PinCell node --> inPinA, inPinB
    std::string LockGNode;     //Contains the name of the G Node for locking
};
```

Instead of 
```
      // Skip Fully Locked Nodes
      if (skipFullyLockedNodes){
        if (fullyLockedNodes.find(i) != fullyLockedNodes.end()){
          UGRAMM->trace("Skipping locked device model node {} for mapping application graph node {} ", gNames[i], hNames[y]);
          continue;
        }
      }
```

Let's do:
```
    if (!(*gConfig)[i].gLocked)
        //Then only do the routeSignal
```

2024-10-17 06:38 UTC, ombhilare999 commented on scripts/device_model_gen.py
> -            MUX_NAME  = ["S", "SW", "W", "NW", "N", "NE", "E", "SE", "PEinA", "PEinB"]
Thanks

2024-10-17 06:43 UTC, ombhilare999 commented on src/UGRAMM.cpp
>    double secondsDRC;
Ohh okay

2024-10-17 06:45 UTC, ombhilare999 commented on lib/UGRAMM.h
> +extern std::set<int> fullyLockedNodes;                  // List of Nodes that are fully locked (i.e. LockGNode for an application graph completely matches to a perticular gNames in device model graph
Hi,
cam you please check this response: https://github.com/UniversalGRAMM/UGRAMM/pull/20#discussion_r1804190436

2024-10-17 06:47 UTC, ombhilare999 commented
Hi @HamasWaqar,
I have completed my reviews, I know the reviews are bit dense but since you have created specialized data structures such as Inverse and all, let's use them to save some run-time and overall, everything looks perfect. Thanks.

2024-10-17 06:49 UTC, ombhilare999 commented on src/utilities.cpp
> +   }
I might have changed verbosity of some of the print statements in the above piece of code, please use your original verbosity level for the printing statements.

2024-10-19 03:04 UTC, HamasWaqar commented on src/utilities.cpp
> +   }
Fixed that change. Thanks Omkar for the simplicity in the design

2024-10-19 03:06 UTC, HamasWaqar commented on src/utilities.cpp
> +bool getLockPE(int HID, json &jsonParsed, std::string& jsonLockNode)
I think that is a great idea. Let me do this

2024-10-19 04:54 UTC, HamasWaqar commented on src/utilities.cpp
> +}
Removed the duplicated function. Also moved the `compatibilityCheck` to the `utilities.cpp` file. Since this function is being used by both DRC and UGRAMM, I thought the `utilities.cpp` file would be the most appropriate location for this function. I honestly don't want to call the function in `routing.cpp` file from `drc.cpp`

2024-10-19 05:12 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +      }
Good idea. Changes has been made

2024-10-19 05:15 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +    }
done

2024-10-19 05:16 UTC, HamasWaqar commented on src/utilities.cpp
> +    }
done

2024-10-20 03:53 UTC, HamasWaqar commented on src/UGRAMM.cpp
> +    int GID = findGNodeID_FuncCell((*hConfig)[y].LockGNode, suitableGIDs);
done

2024-10-20 04:01 UTC, merged